import { Idea } from './types';

export const MOONSHOT_IDEAS: Idea[] = [
  {
    id: 'brain-mimetic-llm',
    title: 'BrainMimetic Intelligence',
    subtitle: 'Engineering Test-Time Plasticity with Titans Architecture to enable continuous learning during inference.',
    date: '2024-05-21',
    status: 'PROTOTYPE',
    impact: 'Infinite Context',
    readTime: '25m',
    tags: ['AGI', 'Titans', 'PyTorch', 'Neuroscience'],
    coverImage: 'https://picsum.photos/seed/titan/800/600?grayscale',
    markdownPath: 'content/brain-mimetic.md',
    featured: true,
  },
  {
    id: 'neuromorphic-llm',
    title: 'Neuromorphic LLM Architecture',
    subtitle: 'My attempt to fix the static weight problem by combining liquid neural networks with transformer attention heads.',
    date: '2023-10-24',
    status: 'PROTOTYPE',
    impact: 'Continuous Learning',
    readTime: '15m',
    tags: ['AI', 'Neuroscience', 'LTC'],
    coverImage: 'https://picsum.photos/800/600?grayscale',
    githubUrl: 'https://github.com/example/neuromorphic',
    featured: false,
    markdownPath: 'content/neuromorphic-llm.md',
    pdfUrl: 'https://arxiv.org/pdf/1706.03762.pdf',
  },
  {
    id: 'biological-compute',
    title: 'Photosynthetic Computation',
    subtitle: 'Harnessing plant biological processes for non-binary logical gates.',
    date: '2023-11-11',
    status: 'CONCEPT',
    impact: 'Zero-Energy Logic',
    readTime: '8m',
    tags: ['Biotech', 'Hardware', 'Moonshot'],
    coverImage: 'https://picsum.photos/800/601?grayscale',
    markdownPath: 'content/biological-compute.md',
  },
  {
    id: 'atmospheric-water',
    title: 'Passive Atmospheric Water Harvesting',
    subtitle: 'Using metamaterials to extract 50L of water per day with zero energy input.',
    date: '2023-12-02',
    status: 'ALPHA',
    impact: 'Decentralized Water',
    readTime: '12m',
    tags: ['Sustainability', 'Material Science'],
    coverImage: 'https://picsum.photos/800/602?grayscale',
    markdownPath: 'content/atmospheric-water.md',
  }
];